services:
  razor-pages:
    image: ${DOCKER_USERNAME:-local}/${IMAGE_NAME:-minitwitimage}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: razor-pages/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./razor-pages/Web/.env
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ISLOCALDEVELOPMENT=${ISLOCALDEVELOPMENT:-false}
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=${CONNECTIONSTRING}
      - API_TOKEN=${API_TOKEN}
      - LOKI_URL=${MONITOR_SSH_HOST}
    volumes:
      - keys-volume:/app/keys
    deploy:
      replicas: 3
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.hostname!=minitwit-db"
          - "node.hostname!=minitwit-test-db"

  promtail:
    image: grafana/promtail:3.6.7
    environment:
      - LOKI_URL=${LOKI_URL}
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command:
      - -config.file=/etc/promtail/config.yaml
      - -config.expand-env=true
    deploy:
      mode: global 
      restart_policy:
        condition: on-failure

volumes:
  keys-volume:
