/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Web.API.Attributes;
using Web.API.Models;
using Web.API.Converters;
using Web.Pages;
using Core.Interfaces;

namespace Web.API.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class MinitwitApiController : ControllerBase
    { 
		private readonly IMessageRepository _messageRepository;
    	private readonly IUserRepository _userRepository;
    	private readonly IFollowerRepository _followerRepository;
        private static int _latest;
        
		public MinitwitApiController(
        	IMessageRepository messageRepository, 
        	IUserRepository userRepository, 
        	IFollowerRepository followerRepository)
    	{
        	_messageRepository = messageRepository;
        	_userRepository = userRepository;
        	_followerRepository = followerRepository;
    	}

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get list of users followed by the given user.  - Query param &#x60;?no&#x3D;&#x60; limits result count. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/fllws/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetFollow")]
        [SwaggerResponse(statusCode: 200, type: typeof(FollowsResponse), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {
            if (!ValidateAuthorization(authorization))
                return Unauthorized();
            
            var user = _userRepository.GetUserByUsername(username);
            if (user == null)
                return UserNotFound();

            var followers = _followerRepository.GetFollowedUsers(user.id).Select(u => u.name).ToList();
            
            if (latest.HasValue)
                _latest = latest.Value;
            
            return new ObjectResult(new FollowsResponse { Follows = followers }) { StatusCode = 200 };
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Returns the latest ID saved</remarks>
        /// <response code="200">Success</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("/latest")]
        [ValidateModelState]
        [SwaggerOperation("GetLatestValue")]
        [SwaggerResponse(statusCode: 200, type: typeof(LatestValue), description: "Success")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        public virtual IActionResult GetLatestValue()
        {
            try
            {
                var response = new LatestValue
                {
                    Latest = _latest
                };
                return new ObjectResult(response) { StatusCode = 200 };
            }
            catch (Exception)
            {
                return BadRequest(new ErrorResponse { Status = 500, ErrorMsg = "Internal Server Error" });
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get recent messages.  - Filters out flagged messages - Returns a list of recent messages (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpGet]
        [Route("/msgs")]
        [ValidateModelState]
        [SwaggerOperation("GetMessages")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ApiMessage>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetMessages([FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {

            if (!ValidateAuthorization(authorization))
                return Unauthorized();
            
            var domainMessages = _messageRepository.GetPublicTimeline();
            var apiMessages = domainMessages.Select(ApiConverters.ToApiMessage).ToList();
            
            if (latest.HasValue)
                _latest = latest.Value;
            
            return new ObjectResult(apiMessages) { StatusCode = 200 };
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get messages for a specific user.  - Returns messages authored by the specified user - Filtered by unflagged - Returns a list of recent messages for the user (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/msgs/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetMessagesPerUser")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ApiMessage>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetMessagesPerUser([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {
            if (!ValidateAuthorization(authorization))
                return Unauthorized();

            if (_userRepository.GetUserByUsername(username) == null)
                return UserNotFound();

            var domainMessages = _messageRepository.GetUserTimeline(username);
            var apiMessages = domainMessages.Select(ApiConverters.ToApiMessage).ToList();
            
            if (latest.HasValue)
                _latest = latest.Value;
            
            return new ObjectResult(apiMessages) { StatusCode = 200 };
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Follow or unfollow a user on behalf of &#x60;username&#x60;.  - Body must contain either &#x60;follow: &lt;user&gt;&#x60; or &#x60;unfollow: &lt;user&gt;&#x60;</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpPost]
        [Route("/fllws/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostFollow")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult PostFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromBody]FollowAction payload, [FromQuery (Name = "latest")]int? latest)
        {
            if (!ValidateAuthorization(authorization))
                return Unauthorized(); 

            if (payload == null)
                return BadRequest(new ErrorResponse { Status = 400, ErrorMsg = "Body must contain either follow or unfollow" });

            var hasFollow = !string.IsNullOrEmpty(payload.Follow);
            var hasUnfollow = !string.IsNullOrEmpty(payload.Unfollow);
            if (hasFollow == hasUnfollow) // both set or both missing
                return BadRequest(new ErrorResponse { Status = 400, ErrorMsg = "Body must contain either follow or unfollow" });

            var who = _userRepository.GetUserByUsername(username);
            if (who == null)
                return UserNotFound();

            var targetUsername = hasFollow ? payload.Follow! : payload.Unfollow!;
            var whom = _userRepository.GetUserByUsername(targetUsername);
            if (whom == null)
                return UserNotFound();

            if (hasFollow)
                _followerRepository.FollowUser(who.id, whom.id);
            else
                _followerRepository.UnfollowUser(who.id, whom.id);

            if (latest.HasValue)
                _latest = latest.Value;
            else
                _latest++;
            
            return NoContent();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Post a new message as a specific user.  - Message must include &#x60;content&#x60; in the body - Stored with timestamp and &#x60;flagged&#x3D;0&#x60; - Returns empty body on success - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpPost]
        [Route("/msgs/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostMessagesPerUser")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult PostMessagesPerUser([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromBody]PostMessage payload, [FromQuery (Name = "latest")]int? latest)
        {
            if (!ValidateAuthorization(authorization))
                return Unauthorized();

            if (payload == null || string.IsNullOrEmpty(payload.Content))
                return BadRequest(new ErrorResponse { Status = 400, ErrorMsg = "Content is required" });

            var user = _userRepository.GetUserByUsername(username);
            if (user == null)
                return UserNotFound();

            _messageRepository.CreateMessage(user.id, payload.Content);
            
            if (latest.HasValue)
                _latest = latest.Value;
            
            return NoContent();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Register a new user. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="400">Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken</response>
        [HttpPost]
        [Route("/register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostRegister")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken")]
        public virtual IActionResult PostRegister([FromBody]RegisterRequest payload, [FromQuery (Name = "latest")]int? latest)
        {
            var username =  payload.Username;
            var email = payload.Email;
            var password = payload.Pwd;
            
            if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password)) 
                return BadRequest(new ErrorResponse { Status = 400, ErrorMsg = "Username or password is missing" });
            
            if (string.IsNullOrEmpty(email) || !email.Contains('@'))
                return BadRequest(new ErrorResponse { Status = 400, ErrorMsg = "Invalid email" });
            
            //TODO: 
            //if (Password != Password2)
            //    Error = "The two passwords do not match";
            
            if (_userRepository.GetUserByUsername(username) != null) 
                return BadRequest(new ErrorResponse { Status = 400, ErrorMsg = "The username is already taken" });

            var hasher = new PasswordHasher<string>();
            var hash = hasher.HashPassword(username, password);
            _userRepository.CreateUser(username, email, hash);
            
            if (latest.HasValue)
                _latest = latest.Value;
            
            return NoContent();
        }

        private bool ValidateAuthorization(string authorization)
        {
            return authorization == $"Basic {Environment.GetEnvironmentVariable("API_TOKEN")}";
        }

        private IActionResult Unauthorized()
        {
            return new ObjectResult(new ErrorResponse
            {
                Status = 403,
                ErrorMsg = "Unauthorized - Must include correct Authorization header"
            });
        }

        private IActionResult UserNotFound()
        {
            return new ObjectResult(new ErrorResponse
            {
                Status = 404,
                ErrorMsg = "User not found"
            });
        }
    }
}
