services:
  prometheus:
    image: prom/prometheus:v3.10.0
    ports:
      - "9090:9090"
    volumes:
      - /vagrant/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    deploy:
      placement:
        constraints: [node.hostname == webserver-monitoring]
      networks:
        - monitor_net
  
  prometheus-dev:
    image: prom/prometheus:v3.10.0
    ports:
      - "9091:9091"
    volumes:
      - /vagrant/monitoring/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-storage-dev:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.listen-address=0.0.0.0:9091'
    deploy:
      placement:
        constraints: [node.hostname == webserver-monitoring]
      networks:
        - monitor_net

  loki:
    image: grafana/loki:3.6.7
    ports:
      - "3100:3100"
    volumes:
      - /vagrant/monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      placement:
        constraints: [node.hostname == webserver-monitoring]
      networks:
        - monitor_net

  loki-dev:
    image: grafana/loki:3.6.7
    ports:
      - "3101:3101"
    volumes:
      - /vagrant/monitoring/loki/loki-dev-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data-dev:/loki
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      placement:
        constraints: [node.hostname == webserver-monitoring]
      networks:
        - monitor_net

  grafana:
    image: grafana/grafana:12.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-temp}
    volumes:
      - grafana-storage:/var/lib/grafana
      - /vagrant/monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - /vagrant/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    deploy:
      placement:
        constraints: [node.hostname == webserver-monitoring]
      restart_policy:
        condition: any
      networks:
        - monitor_net

volumes:
  prometheus-storage:
  prometheus-storage-dev:
  grafana-storage:
  loki-data:
  loki-data-dev:

networks:
  monitor_net:
    driver: overlay
    attachable: true