{
 "title": "Availability PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Up-time (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "up * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expression": "${A} / ${B}", "type": "math" }
   ]
  },
  {
   "title": "Response time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_request_duration_seconds_bucket))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}