{
 "title": "Monitoring PROD",
 "description": "Initial dashboard with initial monitoring visuals.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latest Container status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(up[$__interval])",
     "legendFormat": "status"
    }
   ]
  },
  { "title": "High Level Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Memory (MB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_dotnet_process_memory_working_set / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Request Time (Sec)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_request_duration_seconds_sum) / (sum(http_request_duration_seconds_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tweets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_tweets_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "up",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "min(up{ })", "legendFormat": "status" }
   ]
  },
  {
   "title": "Up-time (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "up * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Tweets",
     "type": "timeseries",
     "description": "The total number of tweets that currently exist in the database",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "minitwit_tweets_total", "legendFormat": "Total_Tweets" }
     ]
    },
    {
     "title": "Total Amount of users",
     "type": "timeseries",
     "description": "Graph Displaying total number of users existing in the database over time",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "minitwit_users_total", "legendFormat": "Total_users" }
     ]
    },
    {
     "title": "Tweet Rate",
     "type": "timeseries",
     "description": "The number of tweets added to the database",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minitwit_tweets_total[1h])",
       "legendFormat": "Total_Tweets"
      }
     ]
    },
    {
     "title": "New User Rate",
     "type": "timeseries",
     "description": "Graph Displaying rate of users added to the database over time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "rate(minitwit_users_total[1h])", "legendFormat": "Total_users" }
     ]
    }
   ]
  },
  {
   "title": "Droplet Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilised by .Net",
     "type": "timeseries",
     "description": "Total known allocated memory from dotnet",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes / 1000000",
       "legendFormat": ".Net Total Memory MB"
      }
     ]
    },
    {
     "title": "Total Physical Allocated Memory",
     "type": "timeseries",
     "description": "The number of bytes of physical memory mapped to the process context.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "system_runtime_dotnet_process_memory_working_set / 1000000",
       "legendFormat": "Allocated Memory"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum(system_runtime_cpu_usage)", "legendFormat": "CPU usage (%)" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Runtime of HTTP Requests",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum by(action) (http_request_duration_seconds_sum) / (sum by(action) (http_request_duration_seconds_count))",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "HTTP GET requests received",
     "type": "timeseries",
     "description": "Total Number of various requests and their returned codes",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by(method, code) (rate(http_requests_received_total{method=\"GET\"}[1h]))",
       "legendFormat": "{{method}} {{code}}"
      }
     ]
    },
    {
     "title": "HTTP POST requests received",
     "type": "timeseries",
     "description": "Total Number of various requests and their returned codes",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by(method, code) (rate(http_requests_received_total{method=\"POST\"}[1h]))",
       "legendFormat": "{{method}} {{code}}"
      }
     ]
    },
    {
     "title": "Login Attempts",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "targets": [
      { "expr": "login_success_total", "legendFormat": "login success total" },
      { "expr": "login_failure_total", "legendFormat": "login failure total" }
     ]
    }
   ]
  }
 ]
}