{
 "title": "Logging PROD",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "replica_1",
   "type": "logs",
   "description": "minitwit_razor-pages.1.* in docker ps",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"minitwit_razor-pages\\\\.1.*\"} |= ``"
    }
   ]
  },
  {
   "title": "replica_2",
   "type": "logs",
   "description": "minitwit_razor-pages.2.* in docker ps",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"minitwit_razor-pages\\\\.2.*\"} |= ``"
    }
   ]
  },
  {
   "title": "replica_3",
   "type": "logs",
   "description": "minitwit_razor-pages.3.* in docker ps",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"minitwit_razor-pages\\\\.3.*\"} |= ``"
    }
   ]
  }
 ]
}