/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.ComponentModel;
using System.Globalization;
using Newtonsoft.Json;
using razor_pages.Models;
using razor_pages.Structs;

namespace razor_pages.Converters
{
    /// <summary>
    /// Custom string to enum converter
    /// </summary>
    public class CustomEnumConverter<T> : TypeConverter
    {
        /// <summary>
        /// Determine if we can convert a type to an enum
        /// </summary>
        /// <param name="context"></param>
        /// <param name="sourceType"></param>
        /// <returns></returns>
        public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        /// <summary>
        /// Convert from a type value to an enum
        /// </summary>
        /// <param name="context"></param>
        /// <param name="culture"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
        {
            var s = value as string;
            if (string.IsNullOrEmpty(s))
            {
                return null;
            }

            return JsonConvert.DeserializeObject<T>(@"""" + value + @"""");
        }
    }

    /// <summary>
    /// Converts domain structs to API (OpenAPI) DTOs for the Minitwit API.
    /// </summary>
    public static class ApiConverters
    {
        /// <summary>API pub_date format matching the spec (e.g. "2019-12-01 12:00:00").</summary>
        private const string PubDateFormat = "yyyy-MM-dd HH:mm:ss";

        public static ApiMessage ToApiMessage(Message message)
        {
            return new ApiMessage
            {
                Content = message.text,
                PubDate = message.pub_date.ToString(PubDateFormat),
                User = message.author.name
            };
        }
    }
}
