---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    #branches:
    #  - main
    #  - master
    
    # Run workflow every time a new tag is pushed to the main branch
    tags:
      - '*'

  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD

# SSH_USER
# SSH_PRIVATE_KEY
# SSH_HOST
# SSH_HOST_TEST
# MONITOR_SSH_HOST

# CONNECTIONSTRING
# API_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Build & push minitwit image
        run: |
          docker buildx build --platform linux/amd64 \
            -t $DOCKER_USERNAME/minitwitimage:${{ github.sha }} \
            -f razor-pages/Dockerfile . --push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}


      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/do_ssh_key
          chmod 600 ~/.ssh/do_ssh_key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Copy config files to all nodes in Docker Swarm cluster
        run: |
          NODES="$SSH_HOST $SSH_HOST_TEST $MONITOR_SSH_HOST"  
          for IP in $NODES; do
            ssh -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no "${SSH_USER}@$IP" 'mkdir -p /vagrant/promtail'
            scp -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no ./promtail/promtail-config.yaml "${SSH_USER}@$IP:/vagrant/promtail/promtail-config.yaml"
          done     
               
          scp -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no ./compose.yaml "${SSH_USER}@${SSH_HOST}:/vagrant/compose.yaml"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_HOST_TEST: ${{ secrets.SSH_HOST_TEST }}
          MONITOR_SSH_HOST: ${{ secrets.MONITOR_SSH_HOST }}

      - name: Deploy to server (using compose)
        run: >
          ssh $SSH_USER@$SSH_HOST -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no
          "export DOCKER_USERNAME='"$DOCKER_USERNAME"' && 
           export IMAGE_NAME='minitwitimage' &&
           export IMAGE_TAG='${{ github.sha }}' && 
           export API_TOKEN='"$API_TOKEN"' &&
           export CONNECTIONSTRING='"$CONNECTIONSTRING"' &&
           export LOKI_URL='https://'"$MONITOR_SSH_HOST"':3100/loki/api/v1/push' &&
           cd /vagrant &&  
           docker stack deploy --with-registry-auth --resolve-image always -c compose.yaml minitwit"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CONNECTIONSTRING: ${{ secrets.CONNECTIONSTRING }}
          LOKI_URL: ${{ secrets.MONITOR_SSH_HOST }}
          