---
name: Continuous Deployment

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD

# SSH_USER
# SSH_PRIVATE_KEY
# SSH_HOST
# SSH_HOST_TEST
# MONITOR_SSH_HOST

# CONNECTIONSTRING
# API_TOKEN
# PROD_LOKI_URL
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Build & push minitwit image
        run: |
          docker buildx build --platform linux/amd64 \
            -t $DOCKER_USERNAME/minitwitimage:${{ github.sha }} \
            -f razor-pages/Dockerfile . --push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/do_ssh_key
          echo "$SSH_KEY_PUB" > ~/.ssh/do_ssh_key.pub
          chmod 600 ~/.ssh/do_ssh_key
          chmod 600 ~/.ssh/do_ssh_key.pub
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
      
      - name: Run Terraform Init
        run: |
          make tf-init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Terraform Apply
        run: |
          cd infrastructure/environments/prod && terraform apply -var-file=prod.tfvars
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_pub_key: "~/.ssh/do_ssh_key.pub"
          TF_VAR_pvt_key: "~/.ssh/do_ssh_key"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy config files to all nodes in Docker Swarm cluster
        run: |
          NODES="$SSH_HOST $SSH_HOST_TEST $MONITOR_SSH_HOST"
          for IP in $NODES; do
            ssh -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no "${SSH_USER}@$IP" \
              'mkdir -p /vagrant/promtail /vagrant/razor-pages/Web && touch /vagrant/razor-pages/Web/.env /vagrant/promtail/.env'
            scp -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no ./promtail/promtail-config.yaml "${SSH_USER}@$IP:/vagrant/promtail/promtail-config.yaml"
          done

          scp -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no ./compose.yaml "${SSH_USER}@${SSH_HOST}:/vagrant/compose.yaml"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_HOST_TEST: ${{ secrets.SSH_HOST_TEST }}
          MONITOR_SSH_HOST: ${{ secrets.MONITOR_SSH_HOST }}

      - name: Install Docker Scout CLI (SonarQube safe)
        run: |
          mkdir -p $HOME/.docker/cli-plugins

          curl --proto "=https" --tlsv1.2 -sSf -L \
            https://github.com/docker/scout-cli/releases/latest/download/docker-scout-linux-amd64 \
            -o $HOME/.docker/cli-plugins/docker-scout

          chmod +x $HOME/.docker/cli-plugins/docker-scout

          docker scout version

      - name: Run Docker Scout CVE scan (SHIFT-LEFT)
        run: |
          docker scout cves minitwit-app:latest \
            --only-severity critical,high \
            --exit-code

      - name: Deploy to server (using compose)
        run: >
          ssh $SSH_USER@$SSH_HOST -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no
          "export DOCKER_USERNAME='"$DOCKER_USERNAME"' && 
           export IMAGE_NAME='minitwitimage' &&
           export IMAGE_TAG='${{ github.sha }}' && 
           export API_TOKEN='"$API_TOKEN"' &&
           export CONNECTIONSTRING='"$CONNECTIONSTRING"' &&
           export PROD_LOKI_URL='"$PROD_LOKI_URL"' &&
           cd /vagrant &&  
           docker stack deploy --with-registry-auth --resolve-image always -c compose.yaml minitwit"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CONNECTIONSTRING: ${{ secrets.CONNECTIONSTRING }}
          PROD_LOKI_URL: ${{ secrets.PROD_LOKI_URL }}
          
