name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
    
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install and Initialize Local PostgreSQL Database
        run: |
          make install-postgres
          make create-postgres-database
        env:
          POSTGRES_LOCAL_USER: ${{ secrets.POSTGRES_LOCAL_USER }}
          POSTGRES_LOCAL_PASSWORD: ${{ secrets.POSTGRES_LOCAL_PASSWORD }}
      
      - name: Create .env files for compose
        run: |
          echo "API_TOKEN=$API_TOKEN" > razor-pages/Web/.env
          echo "CONNECTIONSTRINGS__DEFAULTCONNECTION=$CONNECTIONSTRING" >> razor-pages/Web/.env
          echo "CONNECTIONSTRINGS__TESTCONNECTION=$CONNECTIONSTRING" >> razor-pages/Web/.env
          echo "LOKI_URL=$LOKI_URL" > promtail/.env
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CONNECTIONSTRING: "Server=host.docker.internal;Database=defaultdb;User Id=${{ secrets.POSTGRES_LOCAL_USER }};Password=${{ secrets.POSTGRES_LOCAL_PASSWORD }};"
          LOKI_URL: http://${{ secrets.MONITOR_SSH_HOST }}:3101/loki/api/v1/push

      - name: Build and test Docker image
        run: |
          make build-and-test
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
      
      - name: Clean up local PostgreSQL database
        run: |
          make clean-postgres-database
        env:
          POSTGRES_LOCAL_USER: ${{ secrets.POSTGRES_LOCAL_USER }}
          POSTGRES_LOCAL_PASSWORD: ${{ secrets.POSTGRES_LOCAL_PASSWORD }}