---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    #branches:
    #  - main
    #  - master
    
    # Run workflow every time a new tag is pushed to the main branch
    tags:
      - '*'

  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST
# CONNECTIONSTRING

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx (for docker compose)
#        uses: docker/setup-buildx-action@v3
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
      
      - name: Create .env file for compose
        run: |
          echo "API_TOKEN=$API_TOKEN" > razor-pages/Web/.env
          echo "CONNECTIONSTRINGS__DEFAULTCONNECTION=$CONNECTIONSTRING" >> razor-pages/Web/.env
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CONNECTIONSTRING: ${{ secrets.CONNECTIONSTRING }}
        
      
      - name: Build & push minitwit image
        run: docker compose build && docker compose push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: minitwitimage

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/do_ssh_key
          chmod 600 ~/.ssh/do_ssh_key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Copy .env file to server
        run: scp ./razor-pages/Web/.env $SSH_USER@$SSH_HOST:/vagrant/razor-pages/Web/.env -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy to server (using compose)
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no
          'export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} && cd /vagrant && docker compose pull && docker compose up -d --remove-orphans'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}