name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
    
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      
      - name: Install and Initialize Local PostgreSQL Database
        run: |
          make install-postgres
          make create-postgres-database
        env:
          POSTGRES_LOCAL_USER: ${{ secrets.POSTGRES_LOCAL_USER }}
          POSTGRES_LOCAL_PASSWORD: ${{ secrets.POSTGRES_LOCAL_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create .env file for compose
        run: |
          echo "API_TOKEN=$API_TOKEN" > razor-pages/Web/.env
          echo "CONNECTIONSTRINGS__DEFAULTCONNECTION=$CONNECTIONSTRING" >> razor-pages/Web/.env
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CONNECTIONSTRING: "Server=host.docker.internal;Database=defaultdb;User Id=${{ secrets.POSTGRES_LOCAL_USER }};Password=${{ secrets.POSTGRES_LOCAL_PASSWORD }};"

      - name: Build and test Docker image
        run: |
          make build-and-test
      
      - name: Clean up local PostgreSQL database
        run: |
          make clean-postgres-database
        env:
          POSTGRES_LOCAL_USER: ${{ secrets.POSTGRES_LOCAL_USER }}
          POSTGRES_LOCAL_PASSWORD: ${{ secrets.POSTGRES_LOCAL_PASSWORD }}