name: Compare Secrets
on:
  push:
    branches:
      - chore/loki-url
jobs:
  check-equality:
    runs-on: ubuntu-latest
    steps:
      - name: Compare Secrets
        run: |
          if [ "${{ secrets.LOKI_URL }}" == "${{ secrets.PROD_LOKI_URL }}" ]; then
            echo "The secrets are IDENTICAL."
          else
            echo "The secrets are DIFFERENT."
          fi
